# Site settings
title: Aprenda a Jogar Go Interativamente (Baduk ou Weiqi)
description: >
  Aprenda a Jogar Go Interativamente (Baduk.com.br)
url: "https://baduk.com.br" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
port: 8000

# lessons placeholder
pages: ./_lessons

# default layout for lessons
layout: default

plugins:
- jekyll-watch
- jekyll-assets

# jekyll-assets configuration
assets:
  digest: true
# js_compressor:  uglifier
  css_compressor: scss
  sources:
  - _assets/stylesheets
  - _assets/javascripts